# -*- coding: utf-8 -*-
"""backend_fastAPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xn22AHrP71FAYz8pWrQvQfOLQKEMd8US
"""

from fastapi import FastAPI
from pydantic import BaseModel
import pickle

app = FastAPI()

with open("best_model.pkl", "rb") as f:
    model = pickle.load(f)

with open("target_encoder.pkl", "rb") as f:
    target_encoder = pickle.load(f)

class InputData(BaseModel):
    Gender: str
    Age: float
    Height: float
    Weight: float
    family_history_with_overweight: str
    FAVC: str
    FCVC: float
    NCP: float
    CAEC: str
    SMOKE: str
    CH2O: float
    SCC: str
    FAF: float
    TUE: float
    CALC: str
    MTRANS: str

@app.post("/predict")
def predict(data: InputData):
    d = pd.DataFrame([data.dict()])
    prediction = model.predict(d)
    result = target_encoder.inverse_transform(prediction)[0]
    return {"prediction": result}