# -*- coding: utf-8 -*-
"""frontend_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAXD5WXpRZ1PPmrDevkgkvAFV7YUTPkS
"""

import streamlit as st
import requests

st.title("Obesity Level Predictor")

input_data = {
    "Gender": st.selectbox("Gender", ["Male", "Female"]),
    "Age": st.number_input("Age", 1.0, 100.0),
    "Height": st.number_input("Height (m)", 1.0, 2.5),
    "Weight": st.number_input("Weight (kg)", 20.0, 200.0),
    "family_history_with_overweight": st.selectbox("Family History", ["yes", "no"]),
    "FAVC": st.selectbox("High Calorie Food", ["yes", "no"]),
    "FCVC": st.slider("Vegetable Intake (1-3)", 1.0, 3.0),
    "NCP": st.slider("Main Meals/day", 1.0, 4.0),
    "CAEC": st.selectbox("Food between meals", ["no", "Sometimes", "Frequently", "Always"]),
    "SMOKE": st.selectbox("Smoker", ["yes", "no"]),
    "CH2O": st.slider("Water (1-3)", 1.0, 3.0),
    "SCC": st.selectbox("Monitor Calories", ["yes", "no"]),
    "FAF": st.slider("Physical Activity (0-3)", 0.0, 3.0),
    "TUE": st.slider("Technology Use (0-3)", 0.0, 3.0),
    "CALC": st.selectbox("Alcohol", ["no", "Sometimes", "Frequently", "Always"]),
    "MTRANS": st.selectbox("Transport", ["Public_Transportation", "Walking", "Bike", "Motorbike", "Automobile"])
}

if st.button("Predict"):
    response = requests.post("http://127.0.0.1:8000/predict", json=input_data)
    if response.status_code == 200:
        st.success(f"Prediction: {response.json()['prediction']}")
    else:
        st.error("Prediction failed.")